backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: public/assets
public_folder: assets

builder_types: &builder_types
  - label: 'Text Block'
    name: 'text_block'
    widget: object
    fields:
      - { label: Title, name: title, required: false, widget: text }
      - { label: Text, name: text, widget: markdown }
  - label: 'Image'
    name: 'image'
    widget: object
    fields:
      - { label: Image, name: image, widget: image }
      - { label: Caption, name: caption,  required: false, widget: string }
  - label: 'Floating Image'
    name: 'floating_image'
    widget: object
    fields:
      - { label: Image, name: image, widget: image }
      - { label: Caption, name: caption, required: false, widget: string }
      - { label: Position, name: position, widget: select, default: auto, options: [left, right, auto]}
      - { label: Title, name: title, required: false, widget: text }
      - { label: Text, name: text, widget: markdown }
  - label: Gallery
    name: gallery
    widget: object
    fields:
      - { label: Title, name: title, required: false, widget: text }
      - { label: Gallery Zip, name: gallery, widget: file }

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
        - {label: "Title", name: "title", widget: "text"}
        - {label: "Subtitle", name: "subtitle", widget: "text"}
        - {label: "Slogan", name: "slogan", widget: "string"}
        - {label: "Title Background", name: "background", widget: "image"}
        - {label: "Background Copyright", name: "background_cc", widget: "string"}
        - label: "content"
          name: "content"
          widget: "list"
          types: *builder_types
      - label: "Thanks for getting involved"
        name: "thanks"
        file: "content/thanks.md"
        fields:
        - {label: "Title", name: "title", widget: "text"}
        - {label: "Title Background", name: "background", widget: "image"}
        - {label: "Background Copyright", name: "background_cc", widget: "string"}
        - label: "content"
          name: "content"
          widget: "list"
          types: *builder_types
        