backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: public/assets
public_folder: assets

text_block: &text_block
  name: 'text_block'
  widget: object
  fields:
    - { label: Title, name: title, required: false, widget: text }
    - { label: Text, name: text, widget: markdown }
image: &image
  label: 'Image'
  name: 'image'
  widget: object
  fields:
    - { label: Image, name: image, widget: image }
    - { label: Caption, name: caption,  required: false, widget: string }
double_image: &double_image    
  label: 'Double Image'
  name: 'double_image'
  widget: object
  fields:
    - { label: Left Image, name: left_image, widget: image }
    - { label: Left Caption, name: left_caption,  required: false, widget: string }
    - { label: Right Image, name: right_image, widget: image }
    - { label: Right Caption, name: right_caption,  required: false, widget: string }
gallery: &gallery
  label: Gallery
  name: gallery
  widget: object
  fields:
    - { label: Title, name: title, required: false, widget: text }
    - { label: Gallery Zip, name: gallery, widget: file }
 
basic_types: &basic_types
  - *text_block
  - *image
  - *double_image
  - *gallery

double_column: &double_column
  label: 'Double Column'
  name: 'double_column'
  widget: object
  fields:
    - label: Left Column
      name: left_column
      widget: list
      types: *basic_types
    - label: Right Column 
      name: right_column
      widget: list
      types: *basic_types

block_types: &block_types
  - *text_block
  - *image
  - *double_image
  - *gallery
  - *double_column


collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"
  - name: "pages"
    label: "Pages"
    files:
      
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
        - {label: "Title", name: "title", widget: "text"}
        - {label: "Subtitle", name: "subtitle", widget: "text"}
        - {label: "Slogan", name: "slogan", widget: "string"}
        - {label: "Title Background", name: "background", widget: "image"}
        - {label: "Background Copyright", name: "background_cc", widget: "string"}
        - label: "content"
          name: "content"
          widget: "list"
          types: *block_types
      
      - label: "Thanks for getting involved"
        name: "thanks"
        file: "content/thanks.md"
        fields:
        - {label: "Title", name: "title", widget: "text"}
        - {label: "Title Background", name: "background", widget: "image"}
        - {label: "Background Copyright", name: "background_cc", widget: "string"}
        - label: "content"
          name: "content"
          widget: "list"
          types: *block_types
      
      - label: "James Allen's Story"
        name: "james-allen"
        file: "content/james-allen.md"
        fields:
        - {label: "Title", name: "title", widget: "text"}
        - {label: "Title Background", name: "background", widget: "image"}
        - {label: "Background Copyright", name: "background_cc", widget: "string"}
        - label: "content"
          name: "content"
          widget: "list"
          types: *block_types
        