backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: public/assets
public_folder: assets

 
block_types: &block_types
  - label: Text
    name: text
    widget: object
    fields:
      - { label: Text, name: text, required: false, widget: markdown }
  - label: Image
    name: image
    widget: object
    fields:
      - { label: Image, name: image, widget: image }
      - { label: Caption, name: caption,  required: false, widget: string }
  - label: Double Image
    name: double_image
    widget: object
    fields:
      - { label: Left Image, name: left_image, widget: image }
      - { label: Left Caption, name: left_caption,  required: false, widget: string }
      - { label: Right Image, name: right_image, widget: image }
      - { label: Right Caption, name: right_caption,  required: false, widget: string }
  - label: Gallery
    name: gallery
    widget: object
    fields:
      - { label: Title, name: title, required: false, widget: text }
      - { label: Gallery Zip, name: gallery, widget: file }

single_column: &single_column
  label: Single Column
  name: single_column
  widget: object
  fields:
    - label: Column
      name: content
      widget: list
      types: *block_types

double_column: &double_column
  label: Double Column
  name: double_column
  widget: object
  fields:
    - label: Left Column
      name: left_column
      widget: list
      types: *block_types
    - label: Right Column 
      name: right_column
      widget: list
      types: *block_types


layout_types: &layout_types
  - *single_column
  - *double_column

collections:
  - name: config
    label: Config
    delete: false
    editor:
      preview: false
    files:
      - label: Navigation Bar
        name: navbar
        file: content/navbar.yml
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - label: Page
                name: page
                widget: relation
                collection: pages
                value_field: '{{slug}}'
                search_fields:  [ '{{slug}}' ]
                display_fields: [ '{{slug}}' ]
      - label: Home Page
        name: home_page
        file: content/home.yml
        fields:
        - {label: Title, name: title, widget: text}
        - {label: Subtitle, name: subtitle, widget: text}
        - {label: Slogan, name: slogan, widget: string}
        - {label: Title Background, name: background, widget: image}
        - {label: Background Copyright, name: background_cc, widget: string}
        - label: content
          name: content
          widget: list
          types: *layout_types
      - label: Footer
        name: footer
        file: content/footer.yml
        fields:
          - {label: Company Info, name: company_info, widget: text}
          - {logo: Logo, name: logo, widget: image}
          - {label: Copyright, name: copyright, widget: string}
          - {label: Facebook Link, name: facebook, widget: string}
          - {label: Twitter Link, name: twitter, widget: string}
          - {label: Instagram Link, name: instagram, widget: string}
          - {label: Email Link, name: email, widget: string}
      - label: Site Config
        name: general
        file: config.json
        description: General site settings
        fields:
          - label: URL
            name: base_url
            widget: string
            hint: Do not enter the trailing slash of the URL
          - label: Site title
            name: site_title
            widget: string
          - label: Site description
            name: site_description
            widget: string
          - label: Site keywords
            name: site_keywords
            widget: list
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: string
          - label: Twitter account
            name: twitter_account
            widget: string
          - label: GitHub account
            name: github_account
            widget: string
  - label: Pages
    name: pages
    folder: content/pages
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{path}}'
    identifier_field: title
    fields:
      - {label: Path, name: path, widget: string, pattern: ['^[a-z0-9\-]+$', "Only lowercase letters, numbers, and dashes"]}
      - {label: Title, name: title, widget: text}
      - {label: Title Background, name: background, widget: image}
      - {label: Background Copyright, name: background_cc, widget: string}
      - label: content
        name: content
        widget: list
        types: *layout_types
      