backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: public/assets
public_folder: assets

 
block_types: &block_types
  - name: text
    label: Text
    widget: object
    fields:
      - { name: text, label: Text, widget: markdown, required: false }
  - name: image
    label: Image
    widget: object
    fields:
      - { name: image, label: Image, widget: image }
      - { name: caption,  label: Caption, widget: string, required: false }
      - { name: position, label: Position, widget: select, default: auto, options: [ auto, left, center, right ]}
      - { name: position_mobile, label: Position (Mobile View), widget: select, default: auto, options: [ auto, left, center, right ]}
      - name: width
        label: Relative Width
        widget: select
        default: 1/3
        options: [ 1/4, 1/3, 1/2, { label: 100%, value: full }]
      - name: aspect
        label:  aspect-ratio
        widget: select
        default: 'none'
        options: [ { label: default, value: 'none' }, 1/1, 3/2, 2/3, 4/3, 3/4, 16/9, 9/16 ]
  - name: gallery
    label: Gallery
    widget: object
    fields:
      - { name: title, label: Title, widget: text, required: false }
      - { name: gallery, label: Gallery Zip, widget: file }

single_column: &single_column
  name: single_column
  label: Single Column
  widget: object
  fields:
    - name: content
      label: Column
      widget: list
      types: *block_types

double_column: &double_column
  name: double_column
  label: Double Column
  widget: object
  fields:
    - name: left_column
      label: Left Column
      widget: list
      types: *block_types
    - name: right_column
      label: Right Column 
      widget: list
      types: *block_types


layout_types: &layout_types
  - *single_column
  - *double_column

collections:
  - name: config
    label: Config
    delete: false
    editor:
      preview: false
    files:
      - name: navbar
        label: Navigation Bar
        file: content/navbar.yml
        fields:
          - name: links
            label: Links
            widget: list
            fields:
              - { name: label, label: Label, widget: string }
              - name: page
                label: Page
                widget: relation
                collection: pages
                value_field: '{{slug}}'
                search_fields:  [ '{{slug}}' ]
                display_fields: [ '{{slug}}' ]
      - name: home_page
        label: Home Page
        file: content/home.yml
        fields:
        - { name: title, label: Title, widget: text }
        - { name: subtitle, label: Subtitle, widget: text }
        - { name: slogan, label: Slogan, widget: string }
        - { name: background, label: Title Background, widget: image }
        - { name: background_cc, label: Background Copyright, widget: string }
        - name: content
          label: content
          widget: list
          types: *layout_types
      - name: footer
        label: Footer
        file: content/footer.yml
        fields:
          - { name: company_info, label: Company Info, widget: text }
          - { name: logo, label: Logo, widget: image }
          - { name: copyright, label: Copyright, widget: string }
          - { name: facebook, label: Facebook Link, widget: string }
          - { name: twitter, label: Twitter Link, widget: string }
          - { name: instagram, label: Instagram Link, widget: string }
          - { name: email, label: Email Link, widget: string }
      - name: general
        label: General
        file: config.json
        description: General site settings
        fields:
          - name: base_url
            label: URL
            widget: string
            hint: Do not enter the trailing slash of the URL
          - name: site_title
            label: Site title
            widget: string
          - name: site_description
            label: Site description
            widget: string
          - name: site_keywords
            label: Site keywords
            widget: list
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: string
          - name: twitter_account
            label: Twitter account
            widget: string
          - name: github_account
            label: GitHub account
            widget: string
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{path}}'
    identifier_field: title
    fields:
      - { label: Path, name: path, widget: string, pattern: [ '^[a-z0-9\-]+$', "Only lowercase letters, numbers, and dashes" ] }
      - { label: Title, name: title, widget: text }
      - { label: Title Background, name: background, widget: image }
      - { label: Background Copyright, name: background_cc, widget: string }
      - { label: content, name: content, widget: list, types: *layout_types }
      